### ISSUE TITLE
Fails with NaN

### ISSUE THREAD

**Issue by olalonde** [substack/identity-function#1]
```bash
$ node
> var id = require('identity-function');
undefined
> id(NaN) === NaN
false
```

:(

**Comment by hickford** [comment]
On the contrary:

    > id(NaN)
    NaN

**Comment by pgilad** [comment]
You might want to try:
```js
Number.isNaN(id(NaN)) // -> true
```

**Comment by mstade** [comment]
@hickford is right, `NaN !== NaN` – [for reasons](http://stackoverflow.com/a/1573715).

**Comment by olalonde** [comment]
https://en.wikipedia.org/wiki/Identity_function 

> In equations, the function is given by f(x) = x

So this is not really an identity function?

**Comment by mstade** [comment]
@olalonde – for all intents and purposes, it is. The only value this won't hold true for is `NaN`, because [`NaN !== NaN`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN#Testing_against_NaN) and so the comparison you're making will always fail. This is not a problem with the identity function, it's a problem with how you compare `NaN` with `NaN` – they aren't equal. It is a peculiarity of the JavaScript language (and many other languages that implement IEEE 754-2008,) and I'd be surprised if that behavior would change any time this side of never.

Arguably, your suggestion that because `f(NaN) !== NaN` then it's not an identity function, is academic in nature and still wrong. The value returned from `f(NaN)` will still be `NaN`, it just won't be *equal* to `NaN`. The function is correct, the comparison is flawed. (Btw, `NaN` is the only value that won't strictly equal itself, so that's a test for `NaN` as good as any.)

Does this help you better understand what's going on @olalonde?

**Comment by olalonde** [comment]
I sort of assume this was a "satirical" package given that `var id = require('identity-function');` takes longer to type than `var id = function (x) { return x; }` and jokingly opened this issue. I am now not sure if you guys are just playing along (if so, you had me fooled) or seriously trying to help me so will close for now!
